name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Validate HTML
        uses: Cyb3r-Jak3/html5validator-action@v7.2.0
        with:
          root: '.'
      - name: Check CSS
        run: npx stylelint "assets/css/*.css" --config '{
          "extends": "stylelint-config-standard",
          "rules": {
            "indentation": 2,
            "number-leading-zero": "always"
          }
        }'
